const mongoose = require('mongoose');
const branchRepository = require('../repositories/branch.repository');
const instituteRepository = require('../repositories/institute.repository');
const planRepository = require('../repositories/plan.repository');
const userRepository = require('../repositories/user.repository');
const { auditLog } = require('../utils/auditLogger');
const { paginate } = require('../utils/pagination');

/**
 * BRANCH SERVICE — Business logic for Branch Management
 */

// ── Create Branch & Admin ─────────────────────────────────────────────
const createBranch = async (data, user) => {
  // 1. Verify Institute exists
  const institute = await instituteRepository.findById(user.instituteId);
  if (!institute) throw { status: 404, message: 'Institute not found' };

  // 2. Validate against Subscription Plan limits
  const plan = await planRepository.findById(institute.planId);
  if (!plan) throw { status: 404, message: 'Subscription plan associated with institute not found' };

  const currentBranchCount = await branchRepository.countByInstituteId(user.instituteId);
  if (currentBranchCount >= plan.branchLimit) {
    throw { status: 403, message: `Subscription plan limit reached. You can only have up to ${plan.branchLimit} branches.` };
  }

  // 3. Check duplicates
  const existingCode = await branchRepository.findByCode(data.code);
  if (existingCode) throw { status: 409, message: 'Branch code already in use' };

  const existingEmail = await branchRepository.findByEmail(data.email);
  if (existingEmail) throw { status: 409, message: 'Branch email already in use' };

  const existingAdminEmail = await userRepository.findByEmail(data.adminEmail);
  if (existingAdminEmail) throw { status: 409, message: 'Admin email already in use by another user' };

  // 4. Database Transaction
  const session = await mongoose.startSession();
  session.startTransaction();

  try {
    // Create Branch
    const [branch] = await branchRepository.model.create(
      [
        {
          name: data.name,
          code: data.code,
          email: data.email,
          phone: data.phone,
          address: data.address,
          instituteId: user.instituteId,
          createdBy: user._id,
        },
      ],
      { session }
    );

    // Create Admin User for this Branch
    const [adminUser] = await userRepository.model.create(
      [
        {
          name: data.adminName,
          email: data.adminEmail,
          password: data.adminPassword,
          role: 'BRANCH_ADMIN',
          instituteId: user.instituteId,
          branchId: branch._id,
          createdBy: user._id,
        },
      ],
      { session }
    );

    await session.commitTransaction();
    session.endSession();

    await auditLog({ userId: user._id, role: user.role, action: 'CREATE', resource: 'Branch', resourceId: branch._id });
    await auditLog({ userId: user._id, role: user.role, action: 'REGISTER', resource: 'User', resourceId: adminUser._id, metadata: { note: 'Auto-created during Branch Onboarding' } });

    return { branch, adminUser: { id: adminUser._id, name: adminUser.name, email: adminUser.email } };
  } catch (error) {
    await session.abortTransaction();
    session.endSession();
    throw error;
  }
};

// ── Get All Branches ──────────────────────────────────────────────────
const getAllBranches = async (queryOptions, tenantFilter) => {
  // Apply tenantFilter generated by tenantGuard
  const query = { ...tenantFilter };
  if (queryOptions.status) query.status = queryOptions.status;

  return paginate(branchRepository.model, query, queryOptions);
};

// ── Get Branch by ID ──────────────────────────────────────────────────
const getBranchById = async (id, tenantFilter) => {
  const branch = await branchRepository.findOne({ _id: id, ...tenantFilter });
  if (!branch) throw { status: 404, message: 'Branch not found or access denied' };
  return branch;
};

// ── Update Branch ─────────────────────────────────────────────────────
const updateBranch = async (id, data, user, tenantFilter) => {
  const branch = await branchRepository.findOne({ _id: id, ...tenantFilter });
  if (!branch) throw { status: 404, message: 'Branch not found or access denied' };

  if (data.code && data.code !== branch.code) {
    throw { status: 400, message: 'Branch code cannot be changed once created' };
  }

  const updated = await branchRepository.updateById(id, { ...data, updatedBy: user._id });

  await auditLog({
    userId: user._id, role: user.role,
    action: 'UPDATE', resource: 'Branch', resourceId: id,
    metadata: { changed: Object.keys(data) }
  });

  return updated;
};

// ── Delete (Suspend) Branch ───────────────────────────────────────────
const deleteBranch = async (id, user, tenantFilter) => {
  const branch = await branchRepository.findOne({ _id: id, ...tenantFilter });
  if (!branch) throw { status: 404, message: 'Branch not found or access denied' };

  await branchRepository.softDelete(id, user._id);
  
  // Also suspend all users belonging to this branch
  await userRepository.model.updateMany({ branchId: id }, { isActive: false, updatedBy: user._id });

  await auditLog({ userId: user._id, role: user.role, action: 'SOFT_DELETE', resource: 'Branch', resourceId: id });
};

module.exports = { createBranch, getAllBranches, getBranchById, updateBranch, deleteBranch };
